version: '2'

services:
  # Redis storage for Session data
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '6379:6379'

  # Eureka server for service discovery
  eureka:
    image: 'registry.heroku.com/emarket-eureka/web:latest'
    ports:
      - '8761:8761'

  chatbot-1:
    image: 'registry.heroku.com/emarket-chatbot/web:latest'
    environment:
      - 'BOT_NAME=chatbot1'
      - 'HOST_NAME=emarket-chatbot-1'
      - 'HOST_PORT=5000'
      - 'EUREKA_URI=http://emarket-eureka-server:8761/eureka'
    depends_on:
      - geek-market-eureka-server

  chatbot-2:
    image: 'registry.heroku.com/geek-market-chatbot/web:latest'
    environment:
      - 'BOT_NAME=chatbot2'
      - 'HOST_NAME=emarket-chatbot-2'
      - 'HOST_PORT=5000'
      - 'EUREKA_URI=http://emarket-eureka-server:8761/eureka'
    depends_on:
      - geek-market-eureka-server

  geek-market-chatbot-3:
    image: 'registry.heroku.com/geek-market-chatbot/web:latest'
    environment:
      - 'BOT_NAME=chatbot3'
      - 'HOST_NAME=emarket-chatbot-3'
      - 'HOST_PORT=5000'
      - 'EUREKA_URI=http://emarket-eureka-server:8761/eureka'
    depends_on:
      - geek-market-eureka-server

  geek-market-ui:
    image: 'registry.heroku.com/geek-market-ui/web:latest'
    environment:
      - 'JDBC_DATABASE_URL=jdbc:mysql://host.docker.internal:3306/geek_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC'
      - 'JDBC_DATABASE_USERNAME=root'
      - 'JDBC_DATABASE_PASSWORD=root'
      - 'REDIS_URL=redis'
      - 'HOST_NAME=geek-market-ui'
      - 'EUREKA_URI=http://emarket-eureka-server:8761/eureka'
    ports:
      - '8081:8081'
    depends_on:
      - redis
      - emarket-eureka-server
      - emarket-chatbot-1
      - emarket-chatbot-2
      - emarket-chatbot-3